# Generated by Django 4.2.5 on 2025-08-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeurApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='registreCommerce',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
