# Generated by Django 4.2.5 on 2025-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeurApp', '0003_employerprofile_freelancerprofile_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='portfolio_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
